// AC3 bake-in: fetch the published catalog document and write it into
// the bundle as the offline baseline. Runs in CI before the build with
// CATALOG_URL set (derived from the API url); any failure leaves the
// committed null default — a build must never break on catalog fetch.
//   CATALOG_URL=https://…/catalog node scripts/bake-catalog.mjs
import { writeFileSync } from 'node:fs';

const url = process.env.CATALOG_URL;
const target = new URL('../src/generated/catalogBaseline.ts', import.meta.url);

const write = (doc) =>
  writeFileSync(
    target,
    '// GENERATED by scripts/bake-catalog.mjs — do not edit.\n' +
      "import type { CatalogDoc } from '@/domain/catalogDoc';\n\n" +
      `export const CATALOG_BASELINE: CatalogDoc | null = ${doc ? JSON.stringify(doc) : 'null'};\n`,
  );

if (!url) {
  console.log('bake-catalog: CATALOG_URL not set — keeping the committed baseline');
  process.exit(0);
}
try {
  const response = await fetch(url, { signal: AbortSignal.timeout(15_000) });
  if (response.status === 204) {
    console.log('bake-catalog: server has no published document — baseline stays null');
    write(null);
  } else if (response.ok) {
    const doc = await response.json();
    write(doc);
    console.log(`bake-catalog: baked catalog version ${doc.version}`);
  } else {
    console.warn(`bake-catalog: ${response.status} from ${url} — keeping the committed baseline`);
  }
} catch (err) {
  console.warn(`bake-catalog: fetch failed (${err}) — keeping the committed baseline`);
}
