import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pairProd, sharedOf } from './stack.mjs';

// MUNNI_RENDER_DIR: test override so specs never touch a real rendered/
const OUT_DIR = process.env.MUNNI_RENDER_DIR ?? join(dirname(fileURLToPath(import.meta.url)), '..', 'rendered');

/**
 * First-time runbook, rendered per stack with the ACTUAL values —
 * every inevitably-manual step, in order, nothing generic. Steady-state
 * deploys need none of this.
 */
export function renderRunbook(stack, { minted = [], missingOperator = [] } = {}) {
  const pair = pairProd(stack);
  const isProdTwin = stack.role === 'prod';
  const dir = join(OUT_DIR, stack.stack);
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `runbook.${stack.stack}.md`);
  writeFileSync(file, `# First-time runbook — ${stack.stack}

Generated by \`bootstrap --stack ${stack.stack}\`. Work top to bottom;
every later deploy is automatic. Secrets minted this run: ${minted.length ? minted.join(', ') : 'none'}.
${missingOperator.length ? `\n> ⚠ Operator secrets still MISSING in GitHub Environment \`${stack.githubEnvironment}\`:\n> ${missingOperator.join(', ')} — bootstrap will not verify until they exist.\n` : ''}
## 1. DNS + firewall (once per stack — the only host steps left manual)

Reverse-proxy rules are CODE now: the bootstrap's DSM module creates
them via SYNO.Core.AppPortal.ReverseProxy whenever SYNOLOGY_* creds
are in the environment (the IaC workflow injects them). Rules applied:
${(isProdTwin
  ? [
      [stack.host('web'), stack.ports.web],
      [stack.host('api'), stack.ports.api],
      [stack.host('admin'), stack.ports.admin],
      [stack.host('logto'), stack.ports.logto],
      [stack.host('logtoAdmin'), stack.ports.logtoAdmin],
      [stack.host('glitchtip'), stack.ports.glitchtip],
      [stack.host('vault'), stack.ports.vault],
    ]
  : [
      [stack.host('web'), stack.ports.web],
      [stack.host('api'), stack.ports.api],
      [stack.host('admin'), stack.ports.admin],
    ]
)
  .map(([h, p]) => `- ${h} → localhost:${p}`)
  .join('\n')}

Still manual (probed by --verify, never scripted):
- DNS: the *.${stack.domain} wildcard already covers these subdomains
  when using Synology DDNS; external registrars need the records.
- DSM firewall: allow 172.16.0.0/12 (docker bridge) in the access
  profile — Logto self-fetches its ADMIN_ENDPOINT through the host
  gateway — and RESTRICT ${stack.host('admin')}${isProdTwin ? ` + ${stack.host('logtoAdmin')}` : ''} to LAN.

## 2. Deploy the containers (one workflow click)

The rendered \`docker-compose.${stack.stack}.yml\` + \`.env.${stack.stack}\`
ship through the NAS bundle pipeline: Actions → *Deploy to NAS* → Run
workflow → channel \`${stack.role === 'prod' ? 'iac-prod' : 'iac-staging'}\` (the setup wizard has a button
for it). The NAS poller unpacks the bundle into
\`/volume1/docker/${stack.stack}/\` and runs \`docker compose up -d\` there —
no SSH, no manual copying.
${isProdTwin ? `
## 3. Logto OOBE (ONCE per pair — the single manual auth step)

1. Open ${stack.urls.logtoAdmin} → create the admin user.
2. Applications → Create → Machine-to-machine → name it \`infra\`,
   assign the Logto Management API role (all permissions).
3. Store its credentials:
   \`gh secret set IAC_LOGTO_INFRA_M2M_ID --env ${stack.githubEnvironment}\` and
   \`gh secret set IAC_LOGTO_INFRA_M2M_SECRET --env ${stack.githubEnvironment}\`.
4. Re-run \`bootstrap --stack ${stack.stack}\` — the logto module now
   creates web/admin/native/m2m apps + the API resource as code and
   writes the ids back to the GitHub Environment.
` : `
## 3. Logto apps

Nothing manual — the pair's OOBE happened on ${pair.stack}; re-running
bootstrap creates this stack's apps through the same infra credential.
`}
## 4. GlitchTip (after first boot — one account + one token)

Open ${pair.urls.glitchtip} → register the first account → profile →
Auth Tokens → create a token → store it once per pair:
\`gh secret set IAC_GLITCHTIP_API_TOKEN --env ${pair.githubEnvironment}\`
(the setup wizard does this for you). Re-run bootstrap — the glitchtip
module creates the org + per-stack projects and writes every DSN back
(NAS_API_SENTRY_DSN secret, VITE_GLITCHTIP_DSN/_ADMIN variables) itself.

## 4b. Secrets vault (once per pair — the HUMAN copy)

Vaultwarden runs at ${pair.urls.vault} (LAN-restrict it in the DSM
firewall like the *-admin hosts). Open it → Create account (the master
password is the one secret that lives only in your head) → then store
\`VAULT_SIGNUPS_ALLOWED=false\` as a pair secret and redeploy so
registration closes. Generated GitHub secrets stay write-only — put the
credentials you'll want to look up (GlitchTip login, pgadmin, the infra
M2M) into the vault as you create them; the automated write-back of
minted values (plan SA2) is still on the roadmap.

## 5. Native apps (first upload is Apple/Google-mandated manual)

- Android: trigger \`native-android.yml\` against environment
  \`${stack.githubEnvironment}\` (appId \`${stack.native.appId}\`, label
  "${stack.native.label}", scheme \`${stack.native.scheme}://\`). Download
  the signed .aab artifact → Play Console → create app
  \`${stack.native.appId}\` → upload to Internal testing → grant the CI
  service account. Every later upload is CI.
- iOS: App Store Connect → New App (bundle \`${stack.native.appId}\`) →
  the workflow's TestFlight lane takes over from build 2.
- Store the Play signing SHA-256 back into the stack file if universal
  links are wanted on this pair.

## 6. Verify

\`node infra/bootstrap.mjs --stack ${stack.stack} --verify\` probes web,
api /health, logto well-known and glitchtip and prints anything still
unreachable with the exact fix.
`);
  return file;
}

/**
 * The local family's much shorter runbook: no DNS, no DSM, no GitHub
 * stores — Docker Desktop and the setup wizard. Role-aware: the shared
 * stack and the environment stacks read differently.
 */
export function renderLocalRunbook(stack, { minted = [], missingOperator = [] } = {}) {
  const dir = join(OUT_DIR, stack.stack);
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `runbook.${stack.stack}.md`);
  const compose = `docker compose --env-file .env.${stack.stack} -f docker-compose.${stack.stack}.yml`;
  const shared = stack.sharedStack ? sharedOf(stack) : stack;
  const isShared = stack.role === 'shared';
  const links = isShared
    ? `- glitchtip ${stack.urls.glitchtip} · vault ${stack.urls.vault} · control ${stack.urls.control}`
    : `- app ${stack.urls.web} · admin ${stack.urls.admin} · api ${stack.urls.api}/health
- logto console ${stack.urls.logtoAdmin} · glitchtip (shared) ${shared.urls.glitchtip}`;
  const sharedTail = `
Postgres carries every consumer database (munni_*/logto_* per
environment + glitchtip). munni-control needs the ${stack.controlApi}
environment's sign-in setup before its login works.

## 2. Verify

\`node infra/bootstrap.mjs --stack ${stack.stack} --verify\`
`;
  const envTail = `
## 2. Sign-in as code (zero input via the wizard; by hand:)

1. The wizard seeds the \`infra\` M2M app straight into this env's Logto
   database and re-runs bootstrap. By hand instead: open
   ${stack.urls.logtoAdmin} → claim the console → Applications → Create →
   Machine-to-machine → name it \`infra\`, assign the Logto Management
   API role, then:
   \`$env:IAC_LOGTO_INFRA_M2M_ID='…'; $env:IAC_LOGTO_INFRA_M2M_SECRET='…'; node infra/bootstrap.mjs --stack ${stack.stack}\`
2. \`${compose} up -d\` again so web/admin pick the new runtime config up.

## 3. GlitchTip (optional, once per family)

The wizard mints the admin + token inside the SHARED stack's GlitchTip.
By hand: open ${shared.urls.glitchtip} → register → profile → Auth
Tokens → create →
\`$env:IAC_GLITCHTIP_API_TOKEN='…'; node infra/bootstrap.mjs --stack ${stack.stack}\`
then \`${compose} up -d\` — this environment's DSNs are created and wired.

## 4. Verify

\`node infra/bootstrap.mjs --stack ${stack.stack} --verify\`
`;
  const warn = missingOperator.length
    ? `\n> ⚠ Operator values still missing: ${missingOperator.join(', ')} —\n> export them (e.g. \`$env:NAS_GHCR_PAT='…'\`) and re-run bootstrap.\n`
    : '';
  const storeNote = isShared ? 'THIS store' : `the ${stack.sharedStack} store`;
  writeFileSync(file, `# First-time runbook — ${stack.stack} (local ${isShared ? 'shared services' : 'environment'})

Generated by \`bootstrap --stack ${stack.stack}\`. Secrets live in
\`.secrets.local.json\` next to this file (gitignored; family-wide values
live in ${storeNote}) — re-runs keep them stable.
Minted this run: ${minted.length ? minted.join(', ') : 'none'}.
${warn}
> The setup wizard (\`infra\\setup\\start.cmd\`) does ALL of the below with
> one button — this file is the manual fallback.

## 1. Start ${isShared ? 'the shared services (always first)' : `the environment (after ${stack.sharedStack})`}

From this folder (Docker Desktop running):
\`${compose} up -d\`

${links}
${isShared ? sharedTail : envTail}`);
  return file;
}
