import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pairProd } from './stack.mjs';

const OUT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'rendered');

/**
 * First-time runbook, rendered per stack with the ACTUAL values —
 * every inevitably-manual step, in order, nothing generic. Steady-state
 * deploys need none of this.
 */
export function renderRunbook(stack, { minted = [], missingOperator = [] } = {}) {
  const pair = pairProd(stack);
  const isProdTwin = stack.role === 'prod';
  const dir = join(OUT_DIR, stack.stack);
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `runbook.${stack.stack}.md`);
  writeFileSync(file, `# First-time runbook — ${stack.stack}

Generated by \`bootstrap --stack ${stack.stack}\`. Work top to bottom;
every later deploy is automatic. Secrets minted this run: ${minted.length ? minted.join(', ') : 'none'}.
${missingOperator.length ? `\n> ⚠ Operator secrets still MISSING in GitHub Environment \`${stack.githubEnvironment}\`:\n> ${missingOperator.join(', ')} — bootstrap will not verify until they exist.\n` : ''}
## 1. DNS + firewall (once per stack — the only host steps left manual)

Reverse-proxy rules are CODE now: the bootstrap's DSM module creates
them via SYNO.Core.AppPortal.ReverseProxy whenever SYNOLOGY_* creds
are in the environment (the IaC workflow injects them). Rules applied:
${(isProdTwin
  ? [
      [stack.host('web'), stack.ports.web],
      [stack.host('api'), stack.ports.api],
      [stack.host('admin'), stack.ports.admin],
      [stack.host('logto'), stack.ports.logto],
      [stack.host('logtoAdmin'), stack.ports.logtoAdmin],
      [stack.host('glitchtip'), stack.ports.glitchtip],
    ]
  : [
      [stack.host('web'), stack.ports.web],
      [stack.host('api'), stack.ports.api],
      [stack.host('admin'), stack.ports.admin],
    ]
)
  .map(([h, p]) => `- ${h} → localhost:${p}`)
  .join('\n')}

Still manual (probed by --verify, never scripted):
- DNS: the *.${stack.domain} wildcard already covers these subdomains
  when using Synology DDNS; external registrars need the records.
- DSM firewall: allow 172.16.0.0/12 (docker bridge) in the access
  profile — Logto self-fetches its ADMIN_ENDPOINT through the host
  gateway — and RESTRICT ${stack.host('admin')}${isProdTwin ? ` + ${stack.host('logtoAdmin')}` : ''} to LAN.

## 2. Deploy the containers

The rendered \`docker-compose.${stack.stack}.yml\` + \`.env.${stack.stack}\`
ship through the NAS bundle pipeline (new \`${stack.stack}\` channel in
deploy-nas.yml — IAC4 wires this; until then copy the rendered pair to
\`/volume1/docker/${stack.stack}/\` and \`docker compose up -d\`).
${isProdTwin ? `
## 3. Logto OOBE (ONCE per pair — the single manual auth step)

1. Open ${stack.urls.logtoAdmin} → create the admin user.
2. Applications → Create → Machine-to-machine → name it \`infra\`,
   assign the Logto Management API role (all permissions).
3. Store its credentials:
   \`gh secret set IAC_LOGTO_INFRA_M2M_ID --env ${stack.githubEnvironment}\` and
   \`gh secret set IAC_LOGTO_INFRA_M2M_SECRET --env ${stack.githubEnvironment}\`.
4. Re-run \`bootstrap --stack ${stack.stack}\` — the logto module now
   creates web/admin/native/m2m apps + the API resource as code and
   writes the ids back to the GitHub Environment.
` : `
## 3. Logto apps

Nothing manual — the pair's OOBE happened on ${pair.stack}; re-running
bootstrap creates this stack's apps through the same infra credential.
`}
## 4. GlitchTip DSNs (after first boot)

Open ${pair.urls.glitchtip} → create org \`munni-iac\` + projects
(pwa/api/admin per stack) → store each DSN:
\`gh secret set NAS_API_SENTRY_DSN --env ${stack.githubEnvironment}\`,
\`gh variable set VITE_GLITCHTIP_DSN --env ${stack.githubEnvironment}\`,
\`gh variable set VITE_GLITCHTIP_DSN_ADMIN --env ${stack.githubEnvironment}\`.

## 5. Native apps (first upload is Apple/Google-mandated manual)

- Android: trigger \`native-android.yml\` against environment
  \`${stack.githubEnvironment}\` (appId \`${stack.native.appId}\`, label
  "${stack.native.label}", scheme \`${stack.native.scheme}://\`). Download
  the signed .aab artifact → Play Console → create app
  \`${stack.native.appId}\` → upload to Internal testing → grant the CI
  service account. Every later upload is CI.
- iOS: App Store Connect → New App (bundle \`${stack.native.appId}\`) →
  the workflow's TestFlight lane takes over from build 2.
- Store the Play signing SHA-256 back into the stack file if universal
  links are wanted on this pair.

## 6. Verify

\`node infra/bootstrap.mjs --stack ${stack.stack} --verify\` probes web,
api /health, logto well-known and glitchtip and prints anything still
unreachable with the exact fix.
`);
  return file;
}
