// GENERATED from apollousa CategoryPredictor keyword data by scripts/port-keywords.mjs.
export interface KeywordRule {
  lang: 'nl' | 'en' | 'tr';
  catId: string;
  keywords: string[];
}

export const KEYWORD_RULES: KeywordRule[] = [
  {"lang":"nl","catId":"reimburse","keywords":["terugbetaling","tikkie","betaalverzoek"]},
  {"lang":"nl","catId":"salary","keywords":["salaris","loon","werkgever","uitbetaling"]},
  {"lang":"nl","catId":"freelance","keywords":["freelance","zzp"]},
  {"lang":"nl","catId":"rental","keywords":["huur","verhuur","huurinkomsten"]},
  {"lang":"nl","catId":"investIncome","keywords":["dividend","rente","beleggen","beleggingen"]},
  {"lang":"nl","catId":"housingRent","keywords":["hypotheek","huur","huurtoeslag","huurverhoging","huurcontract","huurwoning","huurhuis","huurprijs","huurachterstand","huurverlaging","onroerendezaakbelasting","ozb","woz-waarde"]},
  {"lang":"nl","catId":"housingUtility","keywords":["gas","water","licht","energie","stroom","waterverbruik","watermeter","waterrekening","waterprijs","waterkosten","waterbedrijf","eneco","essent","nuon","oxxio","vattenfall","energieleverancier","energierekening","energieprijs","energiekosten"]},
  {"lang":"nl","catId":"housingMaintenance","keywords":["feenstra","loodgieter","warmteservice","kewodak"]},
  {"lang":"nl","catId":"housingStorage","keywords":["opslagruimte","self-storage","shurgard","allsafe","boxie24","mijnsafestore","kubox"]},
  {"lang":"nl","catId":"transportCar","keywords":["autoonderdelen","halfords","automaterialen","winparts","autodoc","apk","autoschade"]},
  {"lang":"nl","catId":"parking","keywords":["parking","parkeren","parkmobile","q-park","interparking","p1 parking","yellowbrick","tolvrij","toll"]},
  {"lang":"nl","catId":"bikes","keywords":["swapfiets","fietsenmaker","fietsenwinkel","fietsverhuur","gazelle","vanmoof","batavus","fietsservice"]},
  {"lang":"nl","catId":"telecom","keywords":["kpn","odido","ziggo","vodafone","t-mobile","youfone","simyo","tele2","lebara","lycamobile","hollandsnieuwe","budget thuis","online.nl","caiway","delta fiber"]},
  {"lang":"nl","catId":"transportFuel","keywords":["shell","esso","tango","texaco","avia","argos","gulf","q8","tinq","tankstation","tanken","benzine","diesel","lpg","brandstof","tankpas"]},
  {"lang":"nl","catId":"transportPublic","keywords":["ns","ov-chipkaart","ov","trein","bus","tram","metro","connexxion","arriva","veolia","gvb","ret","htm","qbuzz","syntus","breng","ebs","keolis","ov-fiets","taxi","taxibedrijf","taxicentrale","taxichauffeur","taxi-app","uber"]},
  {"lang":"nl","catId":"groceries","keywords":["jumbo","lidl","plus","dirk","spar","coop","hoogvliet","ekoplaza","jan linders","supermarkt","boodschappen","aldi","albert heijn","picnic","getir","cermefood"]},
  {"lang":"nl","catId":"breakfast","keywords":["ontbijt","brunch","bakkerij","subway","la place","bagels","anne&max","dunkin","firin","lunch"]},
  {"lang":"nl","catId":"restaurants","keywords":["restaurant","bistro","brasserie","burgerbar","vapiano","librije","bord'eau","vinkeles","ciel bleu","mossel&gin","zarzo","bolenius","dozo","momiji","sushi"]},
  {"lang":"nl","catId":"takeout","keywords":["mcdonald's","burger king","kfc","domino's","thuisbezorgd","deliveroo","uber eats","foodora","eazie","hfc hobbemaplein","cigkoftem"]},
  {"lang":"nl","catId":"sweets","keywords":["jamin","baklava","patisserie","snackbar"]},
  {"lang":"nl","catId":"alcohol","keywords":["bier","wijn","sterke drank","slijterij","gall & gall","dirck iii","mitra","drankgigant","drankdozijn","drank.nl","drankoutlet","de jongens"]},
  {"lang":"nl","catId":"tobacco","keywords":["sigaretten","shag","tabak","rookwaren","coffeeshop","tabakszaak","primera"]},
  {"lang":"nl","catId":"coffee","keywords":["starbucks","espresso","coffee","kiosk","koffie","nespresso","douwe egberts","senseo"]},
  {"lang":"nl","catId":"haircut","keywords":["barber","kapper","kapsalon","hairstylist","schorem","toni&guy"]},
  {"lang":"nl","catId":"toiletry","keywords":["etos","shampoo","douchegel","zeep","deodorant","tandpasta","tandenborstel","kruidvat","drogist"]},
  {"lang":"nl","catId":"beautyProduct","keywords":["parfum","bono","douglas","parfumerie","make-up","lippenstift","mascara","oogschaduw","foundation","schoonheidssalon"]},
  {"lang":"nl","catId":"movie","keywords":["pathe","cineville","cinemec","cinema","bioscoop","videoland","pathe thuis"]},
  {"lang":"nl","catId":"concerts","keywords":["concert","festival","theater","musical","opera","ahoy","tivolivredenburg","carré","paradiso","melkweg","doornroosje","013","effenaar","patronaat","oosterpoort","de vereeniging","de vorstin","de helling"]},
  {"lang":"nl","catId":"sportingEvent","keywords":["voetbalwedstrijd","stadium","stadion","feijenoord","arena","kuip","kyocera","adelaarshorst","de goffert","snowworld"]},
  {"lang":"nl","catId":"gambling","keywords":["casino","gokken","gokkast","poker","blackjack","roulette","holland casino"]},
  {"lang":"nl","catId":"hobby","keywords":["kaartenspel","bordspel","audiobook","schilderen","hobby","hobbies","vrijetijdsbesteding","cardmarket","magic: the gathering","yu-gi-oh!","pokémon","bordspellenwinkel","intertoys","bart smit","toychamp","spellenhuis","spellenwinkel","spellenvariant","spellenrijk","audible","storytel","luisterrijk","luisterboeken","manga","stripboek"]},
  {"lang":"nl","catId":"videoGame","keywords":["computerspel","xbox","playstation","nintendo","steam","game mania","nedgame","epic game","ubisoft","activision","bethesda","sony online entertainment","apple arcade","jagex"]},
  {"lang":"nl","catId":"dating","keywords":["datenight","romantisch","valentijnsdag","trouwerij"]},
  {"lang":"nl","catId":"subs","keywords":["netflix","disney+","spotify","apple music","tidal","deezer","youtube","twitch","plex","vimeo","apple tv+","itunes","iptv","ziggo go","npo start","rtl xl"]},
  {"lang":"nl","catId":"entertainmentOther","keywords":["personeelsvereniging"]},
  {"lang":"nl","catId":"gym","keywords":["sportschool","fitness","gym","crossfit","basic-fit","fitforfree","anytime fitness","healthcity","sportcity","trainmore","fit20","fitland"]},
  {"lang":"nl","catId":"sportsEquipment","keywords":["sportkleding","voetbalschoenen","hardloopschoenen","sportwinkel","sportzaak","sportdirect","decathlon","perry sport","aktiesport","intersport","sport2000","sportsworld","blue tomato"]},
  {"lang":"nl","catId":"clothing","keywords":["kleding","h&m","mango","zara","primark","vero moda","forever 21","bershka","g-star raw","jack & jones","bijenkorf","wehkamp","zalando","asos","zeeman","tommy hilfiger"]},
  {"lang":"nl","catId":"electronics","keywords":["coolblue","mediamarkt","conrad","alternate","tweakers","bcc","paradigit","kijkshop","dixons","elektronica","electronics","gopro"]},
  {"lang":"nl","catId":"homeGoods","keywords":["ikea","kwantum","karwei","gamma","praxis","jysk","xenos","action","blokker","hema","v&d","woonaccessoires"]},
  {"lang":"nl","catId":"gift","keywords":["cadeau","gift"]},
  {"lang":"nl","catId":"intimateUtility","keywords":["condoom","sextoy","pabo","easytoys","sexshop"]},
  {"lang":"nl","catId":"festivity","keywords":["halloween","kerst","sinterklaas","pasen","koningsdag","bevrijdingsdag","moederdag","vaderdag","carnaval","oktoberfest"]},
  {"lang":"nl","catId":"houseGarden","keywords":["tuin","tuinwinkel","intratuin"]},
  {"lang":"nl","catId":"homeAutomation","keywords":["hashop","somfy","dedomoticastore","robbshop","smarthomesupply"]},
  {"lang":"nl","catId":"childCare","keywords":["baby","prenatal"]},
  {"lang":"nl","catId":"shoppingOther","keywords":["amazon","aliexpress","temu","alibaba"]},
  {"lang":"nl","catId":"flight","keywords":["klm","transavia","schiphol","cheaptickets","vliegtickets","tix.nl","vueling","corendon","ryanair","easyjet","tuifly","d-reizen","momondo","skyscanner","vliegwinkel","wtc.nl","travelbird","paperflies"]},
  {"lang":"nl","catId":"hotel","keywords":["booking.com","hotel","expedia.nl","trivago","airbnb","agoda"]},
  {"lang":"nl","catId":"carRental","keywords":["europcar","avis","hertz","sunnycars","sixt","alamo","thrifty","cardelmar","easyterra","holidaycars","rentalcars","tui cars","autohuren"]},
  {"lang":"nl","catId":"activity","keywords":["tripadvisor","viator","musement","city discovery"]},
  {"lang":"nl","catId":"tuition","keywords":["duo","studiefinanciering","collegegeld"]},
  {"lang":"nl","catId":"course","keywords":["cursus","training","opleiding","workshop","seminar","webinar","e-learning","coursera","udemy","universiteit"]},
  {"lang":"nl","catId":"book","keywords":["studieboek","book depository","studystore","leesboek","boekenwinkel","boekhandel","kindle","kobo"]},
  {"lang":"nl","catId":"schoolSupply","keywords":["schoolspullen","schooltas","schoolagenda","etui","schriften","kaftpapier","geodriehoek","rekenmachine","rugzak"]},
  {"lang":"nl","catId":"certificate","keywords":["diploma","certificaat","getuigschrift","diplomering","certificering"]},
  {"lang":"nl","catId":"newspaper","keywords":["nrc","volkskrant","telegraaf","trouw","parool","spits","depers"]},
  {"lang":"nl","catId":"doctorVisit","keywords":["huisarts","dokter","fysiotherapeut","gezondheidscentrum","consultatiebureau"]},
  {"lang":"nl","catId":"dental","keywords":["tandarts","orthodontist","mondzorg","ivoren kruis","parodontologie","dental","tandzorg"]},
  {"lang":"nl","catId":"prescription","keywords":["apotheek","medicijnen","medicatie","geneesmiddelen","mediq","pharmeon"]},
  {"lang":"nl","catId":"healthInsurance","keywords":["zorgverzekering","zilveren kruis","menzis","zorg en zekerheid","ditzo","ziezo","zorgdirect","ziektekostenverzekering"]},
  {"lang":"nl","catId":"healthUtility","keywords":["vitamine"]},
  {"lang":"nl","catId":"mentalCare","keywords":["psycholoog","therapeut","psychiater","headspace","psyned","mediteren"]},
  {"lang":"nl","catId":"petFood","keywords":["kattenvoer","hondenbrokken","prins petfoods","versele-laga","smolke","royal canin","pedigree","whiskas","droogvoer","natvoer"]},
  {"lang":"nl","catId":"petSupply","keywords":["dierenwinkel","dierenzaak","pets place","zooplus","max&luna","aquaplantsonline"]},
  {"lang":"nl","catId":"petInsurance","keywords":["dierenverzekering","hondenverzekering","kattenverzekering","petplan","reaal dier & zorg"]},
  {"lang":"nl","catId":"birthday","keywords":["yoursurprise","greetz","hallmark","verjaardag"]},
  {"lang":"nl","catId":"funeralInsurance","keywords":["uitvaartverzekering","monuta","dela"]},
  {"lang":"nl","catId":"charity","keywords":["rode kruis","kika","unicef","greenpeace","natuurmonumenten","kwf kankerbestrijding","hartstichting","donatie"]},
  {"lang":"nl","catId":"taxes","keywords":["belastingdienst"]},
  {"lang":"nl","catId":"fee","keywords":["oranjepakket","paspoort","creditcard","dyme"]},
  {"lang":"nl","catId":"familyCare","keywords":["kinderopvang","gastouder","oppas","nanny","au pair","kinderdagverblijf","babysitter"]},
  {"lang":"nl","catId":"cashWithdraw","keywords":["geldautomaat","geldopname","geldmaat"]},
  {"lang":"nl","catId":"fines","keywords":["boete","cjib"]},
  {"lang":"nl","catId":"uncategorized","keywords":["doker","sahin","dufour","betaalverzoek","tikkie"]},
];
