// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Munni.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Munni.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707074154_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Munni.Api.Data.EntityRow", b =>
                {
                    b.Property<string>("SpaceId")
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("FieldVersionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpaceId", "Entity", "EntityId");

                    b.ToTable("EntityRows");
                });

            modelBuilder.Entity("Munni.Api.Data.Space", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastSeq")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("Munni.Api.Data.SpaceMember", b =>
                {
                    b.Property<string>("SpaceId")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpaceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SpaceMembers");
                });

            modelBuilder.Entity("Munni.Api.Data.SyncOpRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<string>("SpaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId", "OpId")
                        .IsUnique();

                    b.HasIndex("SpaceId", "Seq")
                        .IsUnique();

                    b.ToTable("SyncOps");
                });

            modelBuilder.Entity("Munni.Api.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Sub")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Munni.Api.GoCardless.GcLinkedAccount", b =>
                {
                    b.Property<string>("GcAccountId")
                        .HasColumnType("text");

                    b.Property<string>("AccountEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastFetchAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GcAccountId");

                    b.HasIndex("SpaceId");

                    b.ToTable("GcLinkedAccounts");
                });

            modelBuilder.Entity("Munni.Api.GoCardless.GcRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequisitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GcRequisitions");
                });
#pragma warning restore 612, 618
        }
    }
}
